export type ExamProfile={id:string,name:string,versionRule:string,subjects:string[],difficultyModel:string,assessment:string,official:string[],years:number[]};
export const exams:ExamProfile[]=[
{id:'hkdse',name:'HKDSE',versionRule:'Always anchor to the selected subject examination year and the current HKEAA subject framework.',subjects:['Chinese Language','English Language','Mathematics Compulsory','Mathematics Extended','Biology','Chemistry','Physics','Economics','History','Geography','ICT','BAFS','Chinese History','Literature in English'],difficultyModel:'Calibrate to paper/component, command words, mark allocation, level descriptors, recurring question structures, and current subject-specific marking guidance. Do not treat a mark scheme as a single model answer.',assessment:'Written papers plus subject-specific school-based or practical components where applicable.',official:['https://www.hkeaa.edu.hk/en/hkdse/assessment/assessment_framework/','https://www.hkeaa.edu.hk/en/Resources/publications/list_of_publications/hkdse_erqp_pub/'],years:[2026,2027,2028,2029]},
{id:'ap',name:'AP',versionRule:'Use the current course and exam description and the latest released materials available for that course.',subjects:['Biology','Chemistry','Calculus AB','Calculus BC','Precalculus','Physics 1','Physics 2','Psychology','US History','World History','English Language','English Literature','Computer Science A','Statistics','Human Geography'],difficultyModel:'Match the current course skill categories, MCQ/FRQ proportions, command verbs, scoring guidelines, sample responses, and evidence-based score-setting. Include rubrics for constructed responses.',assessment:'Most exams combine computer-scored multiple choice with free response, essays, projects, or other subject-specific components.',official:['https://apcentral.collegeboard.org/courses/exam-dates','https://apcentral.collegeboard.org/courses/how-ap-develops-courses-and-exams/score-setting-and-scoring','https://apcentral.collegeboard.org/courses'],years:[2026,2027,2028]},
{id:'ibdp',name:'IB Diploma',versionRule:'Subject guide and first-assessment year control the format. Never mix old and current subject structures silently.',subjects:['English A','English B','Mathematics AA','Mathematics AI','Biology','Chemistry','Physics','Economics','History','Geography','Computer Science','Psychology'],difficultyModel:'Match subject-specific assessment objectives, command terms, paper structure, internal/external assessment, markscheme language, and exemplar performance levels.',assessment:'External examinations plus internal assessment and other subject-specific components.',official:['https://www.ibo.org/programmes/diploma-programme/assessment-and-exams/','https://www.ibo.org/programmes/diploma-programme/assessment-and-exams/sample-exam-papers/'],years:[2026,2027,2028]},
{id:'sat',name:'SAT',versionRule:'Use the current digital SAT content domains and module/adaptive rules.',subjects:['Reading and Writing','Math'],difficultyModel:'Calibrate to official content domains, skills, item type, digital format, and difficulty bands. Preserve distractor logic and concise wording.',assessment:'Digital adaptive test with Reading and Writing and Math modules.',official:['https://satsuite.collegeboard.org/sat/whats-on-the-sat','https://satsuite.collegeboard.org/practice/student-question-bank'],years:[2026,2027,2028]},
{id:'toefl',name:'TOEFL iBT',versionRule:'For tests on/after 21 Jan 2026 use the updated adaptive format and 1–6 score scale.',subjects:['Reading','Listening','Writing','Speaking'],difficultyModel:'Match current task types, academic context, adaptive behavior, timing, integrated skills, and official performance descriptors.',assessment:'Adaptive computer-based assessment of four academic communication skills.',official:['https://www.ets.org/toefl/test-takers/ibt/about/content.html','https://www.ets.org/toefl/test-takers/ibt/scores/understand-scores.html'],years:[2026,2027,2028]},
{id:'alevel',name:'Cambridge International A Level',versionRule:'Use the current syllabus code and examination series.',subjects:['Mathematics','Further Mathematics','Biology','Chemistry','Physics','Economics','Computer Science','History','Geography','English Language','English Literature'],difficultyModel:'Match syllabus assessment objectives, command words, paper/component structure, grade descriptors and examiner commentary when available.',assessment:'Component/paper based subject examinations, often with practical or coursework components.',official:['https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-international-as-and-a-levels/'],years:[2026,2027,2028]},
{id:'act',name:'ACT',versionRule:'Use the current section structure and test date rules.',subjects:['English','Math','Reading','Science','Writing'],difficultyModel:'Match current section blueprint, content domains, timing, question types and official practice material.',assessment:'Standardized college-admissions assessment with multiple-choice sections and optional writing.',official:['https://www.act.org/content/act/en/products-and-services/the-act/test-preparation/act-exam-sections-and-structure.html'],years:[2026,2027,2028]},
{id:'ielts',name:'IELTS Academic',versionRule:'Use the current Academic test format and band descriptors.',subjects:['Listening','Reading','Writing','Speaking'],difficultyModel:'Match task types, timing, lexical/grammar demands, coherence, pronunciation and official band descriptors.',assessment:'Four-skill academic English test with task-specific scoring.',official:['https://ielts.org/take-a-test/test-types/ielts-academic-test'],years:[2026,2027,2028]},
{id:'university',name:'College / University',versionRule:'Use the instructor syllabus, course outline, learning objectives and supplied past exams as primary authority.',subjects:['Custom subject'],difficultyModel:'Infer question archetypes, cognitive demand, rubric and grading strictness from the supplied syllabus, lectures, assignments, exams and marking guides.',assessment:'Course-specific. The app must never pretend generic difficulty equals a particular professor’s exam.',official:[],years:[2026,2027,2028,2029] },
{id:'custom',name:'Custom Examination',versionRule:'User-provided sources are authoritative unless the user explicitly selects an external specification.',subjects:['Custom subject'],difficultyModel:'Build a calibration profile from supplied materials, example questions, rubrics and user target.',assessment:'User-defined.',official:[],years:[2026,2027,2028,2029] }
];
export function examById(id:string){return exams.find(e=>e.id===id);}
